-- kraje
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AFG', 'Afganistan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ALB', 'Albania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AND', 'Andora');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AGO', 'Angola');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AIA', 'Anguilla');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ATA', 'Antarktyka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ATG', 'Antigua i Barbuda');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SAU', 'Arabia Saudyjska');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ARG', 'Argentyna');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ARM', 'Armenia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ABW', 'Aruba');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AUS', 'Australia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AUT', 'Austria');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('AZE', 'Azerbejd¿an');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BHS', 'Bahamy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BHR', 'Bahrajn');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BGD', 'Bangladesz');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BRB', 'Barbados');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BEL', 'Belgia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BLZ', 'Belize');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BEN', 'Benin');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BMU', 'Bermudy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BTN', 'Bhutan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BLR', 'Bia³oruœ');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BOL', 'Boliwia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BES', 'Bonaire, Sint Eustatius i Saba');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BIH', 'Boœnia i Hercegowina');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BWA', 'Botswana');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BRA', 'Brazylia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BRN', 'Brunei');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IOT', 'Brytyjskie Terytorium Oceanu Indyjskiego');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VGB', 'Brytyjskie Wyspy Dziewicze');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BGR', 'Bu³garia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BFA', 'Burkina Faso');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BDI', 'Burundi');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CHL', 'Chile');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CHN', 'Chiny');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('HRV', 'Chorwacja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CUW', 'Curaçao');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CYP', 'Cypr');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TCD', 'Czad');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MNE', 'Czarnogóra');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CZE', 'Czechy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('UMI', 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('DNK', 'Dania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('COD', 'Demokratyczna Republika Konga');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('DMA', 'Dominika');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('DOM', 'Dominikana');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('DJI', 'D¿ibuti');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('EGY', 'Egipt');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ECU', 'Ekwador');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ERI', 'Erytrea');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('EST', 'Estonia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SWZ', 'Eswatini');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ETH', 'Etiopia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('FLK', 'Falklandy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('FJI', 'Fid¿i');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PHL', 'Filipiny');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('FIN', 'Finlandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('FRA', 'Francja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ATF', 'Francuskie Terytoria Po³udniowe i Antarktyczne');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GAB', 'Gabon');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GMB', 'Gambia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SGS', 'Georgia Po³udniowa i Sandwich Po³udniowy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GHA', 'Ghana');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GIB', 'Gibraltar');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GRC', 'Grecja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GRD', 'Grenada');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GRL', 'Grenlandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GEO', 'Gruzja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GUM', 'Guam');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GGY', 'Guernsey');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GUF', 'Gujana Francuska');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GUY', 'Gujana');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GLP', 'Gwadelupa');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GTM', 'Gwatemala');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GNB', 'Gwinea Bissau');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GNQ', 'Gwinea Równikowa');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GIN', 'Gwinea');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('HTI', 'Haiti');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ESP', 'Hiszpania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NLD', 'Holandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('HND', 'Honduras');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('HKG', 'Hongkong');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IND', 'Indie');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IDN', 'Indonezja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IRQ', 'Irak');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IRN', 'Iran');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IRL', 'Irlandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ISL', 'Islandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ISR', 'Izrael');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('JAM', 'Jamajka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('JPN', 'Japonia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('YEM', 'Jemen');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('JEY', 'Jersey');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('JOR', 'Jordania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CYM', 'Kajmany');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KHM', 'Kambod¿a');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CMR', 'Kamerun');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CAN', 'Kanada');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('QAT', 'Katar');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KAZ', 'Kazachstan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KEN', 'Kenia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KGZ', 'Kirgistan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KIR', 'Kiribati');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('COL', 'Kolumbia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('COM', 'Komory');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('COG', 'Kongo');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KOR', 'Korea Po³udniowa');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PRK', 'Korea Pó³nocna');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CRI', 'Kostaryka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CUB', 'Kuba');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KWT', 'Kuwejt');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LAO', 'Laos');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LSO', 'Lesotho');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LBN', 'Liban');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LBR', 'Liberia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LBY', 'Libia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LIE', 'Liechtenstein');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LTU', 'Litwa');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LUX', 'Luksemburg');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LVA', '£otwa');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MKD', 'Macedonia Pó³nocna');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MDG', 'Madagaskar');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MYT', 'Majotta');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MAC', 'Makau');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MWI', 'Malawi');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MDV', 'Malediwy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MYS', 'Malezja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MLI', 'Mali');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MLT', 'Malta');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MNP', 'Mariany Pó³nocne');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MAR', 'Maroko');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MTQ', 'Martynika');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MRT', 'Mauretania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MUS', 'Mauritius');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MEX', 'Meksyk');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('FSM', 'Mikronezja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MMR', 'Mjanma');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MDA', 'Mo³dawia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MCO', 'Monako');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MNG', 'Mongolia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MSR', 'Montserrat');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MOZ', 'Mozambik');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NAM', 'Namibia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NRU', 'Nauru');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NPL', 'Nepal');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('DEU', 'Niemcy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NER', 'Niger');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NGA', 'Nigeria');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NIC', 'Nikaragua');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NIU', 'Niue');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NFK', 'Norfolk');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NOR', 'Norwegia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NCL', 'Nowa Kaledonia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('NZL', 'Nowa Zelandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('OMN', 'Oman');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PAK', 'Pakistan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PLW', 'Palau');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PSE', 'Palestyna');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PAN', 'Panama');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PNG', 'Papua-Nowa Gwinea');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PRY', 'Paragwaj');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PER', 'Peru');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PCN', 'Pitcairn');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PYF', 'Polinezja Francuska');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('POL', 'Polska');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PRI', 'Portoryko');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('PRT', 'Portugalia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ZAF', 'Po³udniowa Afryka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CAF', 'Republika Œrodkowoafrykañska');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CPV', 'Republika Zielonego Przyl¹dka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('REU', 'Reunion');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('RUS', 'Rosja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ROU', 'Rumunia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('RWA', 'Rwanda');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ESH', 'Sahara Zachodnia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('KNA', 'Saint Kitts i Nevis');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LCA', 'Saint Lucia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VCT', 'Saint Vincent i Grenadyny');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BLM', 'Saint-Barthélemy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MAF', 'Saint-Martin');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SPM', 'Saint-Pierre i Miquelon');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SLV', 'Salwador');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ASM', 'Samoa Amerykañskie');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('WSM', 'Samoa');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SMR', 'San Marino');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SEN', 'Senegal');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SRB', 'Serbia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SYC', 'Seszele');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SLE', 'Sierra Leone');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SGP', 'Singapur');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SXM', 'Sint Maarten');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SVK', 'S³owacja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SVN', 'S³owenia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SOM', 'Somalia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('LKA', 'Sri Lanka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('USA', 'Stany Zjednoczone');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SDN', 'Sudan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SSD', 'Sudan Po³udniowy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SUR', 'Surinam');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SJM', 'Svalbard i Jan Mayen');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SYR', 'Syria');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CHE', 'Szwajcaria');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SWE', 'Szwecja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TJK', 'Tad¿ykistan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('THA', 'Tajlandia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TWN', 'Tajwan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TZA', 'Tanzania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TLS', 'Timor Wschodni');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TGO', 'Togo');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TKL', 'Tokelau');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TON', 'Tonga');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TTO', 'Trynidad i Tobago');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TUN', 'Tunezja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TUR', 'Turcja');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TKM', 'Turkmenistan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TCA', 'Turks i Caicos');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('TUV', 'Tuvalu');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('UGA', 'Uganda');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('UKR', 'Ukraina');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('URY', 'Urugwaj');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('UZB', 'Uzbekistan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VUT', 'Vanuatu');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('WLF', 'Wallis i Futuna');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VAT', 'Watykan');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VEN', 'Wenezuela');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('HUN', 'Wêgry');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('GBR', 'Wielka Brytania');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VNM', 'Wietnam');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ITA', 'W³ochy');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CIV', 'Wybrze¿e Koœci S³oniowej');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('BVT', 'Wyspa Bouveta');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CXR', 'Wyspa Bo¿ego Narodzenia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('IMN', 'Wyspa Man');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SHN', 'Wyspa Œwiêtej Heleny, Wyspa Wniebowst¹pienia i Tristan da Cunha');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ALA', 'Wyspy Alandzkie');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('COK', 'Wyspy Cooka');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('VIR', 'Wyspy Dziewicze Stanów Zjednoczonych');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('HMD', 'Wyspy Heard i McDonalda');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('CCK', 'Wyspy Kokosowe');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('MHL', 'Wyspy Marshalla');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('FRO', 'Wyspy Owcze');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('SLB', 'Wyspy Salomona');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('STP', 'Wyspy Œwiêtego Tomasza i Ksi¹¿êca');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ZMB', 'Zambia');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ZWE', 'Zimbabwe');
INSERT INTO kraje (kod_kraju, nazwa) VALUES ('ARE', 'Zjednoczone Emiraty Arabskie'); 

-- style

INSERT INTO style (nazwa, opis) VALUES ('Witbier', XMLTYPE('<opis>Lekkie, orzeŸwiaj¹ce, zmêtnione, wysokonasycone, bardzo jasne ale o przyjemnym owocowo-przyprawowym aromacie i niskiej goryczce. Du¿y udzia³ nies³odowanej pszenicy wp³ywa na znaczne zmêtnienie oraz nadaje piwu charakterystyczny smak. Barwa, poziom goryczki, zmêtnienie i wysycenie podobne jak w przypadku bawarskiego weissbiera. Aromat i smak owocowy i przyprawowy witbiera pochodz¹ bardziej z u¿ytych dodatków ni¿ z procesu fermentacji. Charakter przyprawowy jest bardziej pieprzowy, ni¿ goŸdzikowy, a owocowoœæ ma bardziej cytrusowy ni¿ bananowo-gruszkowy charakter z jakim spotkamy siê w weissbierze.</opis>'));
INSERT INTO style (nazwa, opis) VALUES ('AIPA', XMLTYPE('<opis>Zdecydowanie chmielowe, nowofalowe, jasne, pe³ne, wytrawne, gorzkie amerykañskie piwo górnej fermentacji. Ten opis odnosi siê do klasycznej, jasnej, czystej i zdominowanej przez chmiel interpretacji stylu, nazywanej czasem west coast IPA, dla odró¿nienia od bardziej zbalansowanych IPA popularnych na wschodnim wybrze¿u USA (east coast IPA) Piwa bardziej s³odowe, ciemniejsze lub o wyraŸnym charakterze pochodz¹cym z fermentacji opisane s¹ w innych pozycjach tego Kompendium.</opis>'));

-- browary
INSERT INTO browary (nazwa, data_zalozenia, kod_kraju) VALUES ('Pinta', TO_DATE('2011-05-07', 'YYYY-MM-DD'), 'POL');
INSERT INTO browary (nazwa, data_zalozenia, kod_kraju) VALUES ('Browar Kormoran', TO_DATE('1993-03-07', 'YYYY-MM-DD'), 'POL');
INSERT INTO browary (nazwa, data_zalozenia, kod_kraju) VALUES ('Browar Amber', TO_DATE('1994-11-24', 'YYYY-MM-DD'), 'POL');

-- konta
INSERT INTO konta (nazwa, typ) VALUES ('Gerwazy', 'piwowar');
INSERT INTO konta (nazwa, typ) VALUES ('Talar', 'uzytkownik');


-- piwowarzy
INSERT INTO piwowarzy (id_konta, id_browaru) VALUES (1, 1);

-- miejscowosci
INSERT INTO miejscowosci (nazwa, kod_kraju) VALUES ('£osice', 'POL');
INSERT INTO miejscowosci (nazwa, kod_kraju) VALUES ('Rzeczyca', 'POL');

-- uzytkownicy
INSERT INTO uzytkownicy (id_konta, data_urodzenia, plec, numer_miejscowosci, kod_kraju) VALUES (2, TO_DATE('2002-07-05', 'YYYY-MM-DD'), 'M', 1, 'POL');


-- piwa
INSERT INTO piwa (numer_piwa, nazwa, opis, zawartosc_alkoholu, zawartosc_ekstraktu, goryczka, barwa, id_browaru, id_stylu)
VALUES (1, 'Atak Chmielu', 'PINTA Atak Chmielu to fantazyjnie nachmielone piwo w stylu American India Pale Ale.
Czerwono-miedziane, treœciwe, ze smakiem i aromatem cytrusowym, kwiatowym, ¿ywicznym, sosnowym i owocowym, pochodz¹cym od amerykañskiego chmielu. Fermentowane z u¿yciem dro¿d¿y Safale US-05 w temp. 18-19°C.

Sk³ad: woda; s³ody: Weyermann®, Pale Ale, melanoidynowy, Carahell®, Carapils®; chmiele (USA): Citra, Simcoe, Cascade, Amarillo; dro¿d¿e: Safale US-05.', 6.1, 15.1, 60, 28, 1, 1);

-- recenzje
INSERT INTO recenzje (czas_recenzji, ocena_ogolna, smak, wyglad, aromat, id_uzytkownika, id_browaru, numer_piwa, komentarz)
VALUES (TO_TIMESTAMP('2019-03-08 15:57:11020', 'YYYY-MM-DD HH24:MI:SSFF3'), 8, 8, 8, 9, 1, 1, 1, 'Powrót do klasyki po paru dobrych latach. Po wielu negatywnych opiniach które s³ysza³em o tym piwie, ¿e siê zepsu³o, ¿e jest strasznie karmelowe, itp. Muszê stwierdziæ, ¿e spodziewa³em siê du¿o gorszego piwa. Co prawda Atak nie jest tak dobry, jak za swoich najlepszych lat, ale jest to dalej fantastyczne piwo. Co do karmelu, to faktycznie jest go sporo, choæ znakomicie ³¹czy siê z mocn¹ i zalegaj¹c¹ goryczk¹. Karmel wspaniale tak¿e ³¹czy siê w aromacie i smaku z nutami chmielowymi tworz¹c \"zabójcz¹\" mieszankê. Pijalnoœæ bardzo dobra, piwo nie ma wad (choæ mo¿e lekki diacetyl siê pojawia). Fantastyczna rzecz.');
